### ISSUE TITLE
Questions about the package

### ISSUE THREAD

**Issue by rafael-guerra-www** [baggepinnen/DynamicAxisWarping.jl#64]
The questions are formulated in the attached picture but in summary, for the 1D case:
- Why continuing linking points in the two input curves when one of them is exhausted?
- Do the input curves need to have the same start and end points and sampling rate?

![DynamicTimeWarping_DTW_questions_for_FC](https://github.com/baggepinnen/DynamicAxisWarping.jl/assets/20739393/88bd3580-07b1-45d4-966d-01cc3d53fdb4)

**Comment by baggepinnen** [comment]
> Why continuing linking points in the two input curves when one of them is exhausted?

The definition of the DTW semi-metric is to match each point in one segment with one from the other segment

> Do the input curves need to have the same start and end points and sampling rate?

No, you can use two completely arbitrary series of numbers. Sampling rate is not a concept in this package. 

Both of your questions are questions about dynamic time warping rather than about this particular implementation of DTW. I recommend studying the [wikipedia page](https://en.wikipedia.org/wiki/Dynamic_time_warping) and the reference therein to learn more about DTW and whether or not it is a suitable metric for your usecase.

**Comment by rafael-guerra-www** [comment]
Thank you Fredrik, much appreciated.
